[WIP] Add Libnotify::Notification (OO wrap)
splattael/libnotify.cr pull request #2
Opened 2016-10-18 14:00 UTC by Nephos

Hello

I made this draft.

Do you feel comfortable with it and do I continue ?

2016-10-18 15:19 UTC, splattael requested changes
Wow, good job! :tada: :green_heart:

I like it very much :)

Please see my comments below!

2016-10-18 15:19 UTC, splattael commented on spec/libnotify_spec.cr
> +require "./notification_spec"
I don't think you need to `require` the spec here. It will be automatically picked by `make spec`.

2016-10-18 15:19 UTC, splattael commented on src/libnotify/notification.cr
> +      update!
I would not update the notification on each assignment.

Similar to Ruby's [libnotify](https://github.com/splattael/libnotify) API I love to this:

```crystal
n = Libnotify.new(summary: "hello", body: "world")
n.update # identical to show! if not shown before

n.update(body: "my love") do |notify|
  notify.summary = "goodbye"
end
```

With API above, generating code with macros could be deleted.

WDYT?

2016-10-18 15:42 UTC, Nephos commented on spec/libnotify_spec.cr
> +require "./notification_spec"
ok !

2016-10-18 15:45 UTC, Nephos commented on src/libnotify/notification.cr
> +      update!
seems good to me too

2016-10-18 16:22 UTC, Nephos commented on src/libnotify/notification.cr
> +      update!
fixed

2016-10-18 16:22 UTC, Nephos commented on spec/libnotify_spec.cr
> +require "./notification_spec"
fixed

2016-10-18 16:35 UTC, Nephos commented
I don't feel comfortable with the current Notification specs, but I don't see if it is possible to do better with the current libnotify api.

I'm good with these changes.

Anything we could add ?

Maybe could we remove the ``$`` in the readme, because there are not necessary and avoid copy/paste :question: 
Do you know if ``get_closed_reason`` must be use in a specific context or anything ?

2016-10-19 06:53 UTC, splattael requested changes
Again, thanks for your awesome work :green_heart: I appreciate it very much!

Regarding your questions:

> Anything we could add ?

I'm fine the volume of your API changes. More ideas could go into new PRs :)

> Maybe could we remove the $ in the readme, because there are not necessary and avoid copy/paste

Good idea! New PR would be great for that.

> Do you know if `get_closed_reason` must be use in a specific context or anything ?

According to `Notify`'s [docs](https://people.gnome.org/~gcampagna/docs/Notify-0.7/Notify.Notification.get_closed_reason.html):
`Returns the closed reason code for the notification. This is valid only after the "closed" signal is emitted.`

As we do not handle "close" events I'd ignore this feature for now :)

I have 3 more comments below.

Thanks again :clap:

2016-10-19 06:53 UTC, splattael commented on src/libnotify/notification.cr
> +    C.notification_show @notify, gerror
I wonder if we could call here `update` every time so need of chaining these calls `libnotify.update.show` will disappear.

Another solution would be to let `update` accept the same arguments (and block) as `Libnotify.new` like:

```crystal
notify = Libnotify.new
notify.update(body: "summary") do |n|
  n.timeout = 23
end
# no need to call `.show`
```

Which one do you like? :)

2016-10-19 06:53 UTC, splattael commented on src/libnotify/notification.cr
> +  def to_unsafe
Why is this needed?

2016-10-19 06:53 UTC, splattael commented on src/libnotify/notification.cr
> +  def timeout=(sec : Float::Primitive)
Similar to Ruby's libnotify I'd like to have a distinction between `Int32` (`Int64` maybe?), `Float` and `String`.
In Crystal, we can implement with method-overloading pretty elegantly so we don't have to this `case/when` dance like in Ruby: https://github.com/splattael/libnotify/blob/5d908930a8cd48a2e46c39235f5daf9d1c67bfff/lib/libnotify/api.rb#L84,L99

WDYT?

2016-10-19 08:25 UTC, Nephos commented on src/libnotify/notification.cr
> +  def to_unsafe
If someone wants to use a advanced function (like ``notify_notification_set_hint_string``), he has to use the internal pointer, isn't it ?

2016-10-19 08:27 UTC, Nephos commented on src/libnotify/notification.cr
> +  def timeout=(sec : Float::Primitive)
yeah.
There is a default setter (Int32, in milliseconds) and a setter (Float in seconds)

`property timeout : Int32`
`def timeout=(sec : Float::Primitive)`

2016-10-19 08:30 UTC, Nephos commented on src/libnotify/notification.cr
> +    C.notification_show @notify, gerror
The second is very elegant. But I think the first one is less surprising

2016-10-19 08:31 UTC, splattael commented on src/libnotify/notification.cr
> +  def to_unsafe
Do you have a concrete case for this usage? If not, I'd rather leave it out for now.
People still can complain about the missing `to_unsafe` if they need it ;)
Opinions?

2016-10-19 08:31 UTC, splattael commented on src/libnotify/notification.cr
> +  def timeout=(sec : Float::Primitive)
:+1:

2016-10-19 08:43 UTC, Nephos commented on src/libnotify/notification.cr
> +  def to_unsafe
I think I don't have, it must be very special cases. I guess if really needed, they can use the C functions without using the objects.

2016-10-19 08:54 UTC, Nephos commented on src/libnotify/notification.cr
> +  def to_unsafe
fixed

2016-10-19 09:06 UTC, Nephos commented on src/libnotify/notification.cr
> +    C.notification_show @notify, gerror
I just published a commit where there are these modifications.
I don't like to call `show` in the `update` method, it's not the work of `update`.

- update (can take a block) modify the fields (no
- show update the notification and display it

2016-10-19 10:04 UTC, Nephos commented
> > Do you know if get_closed_reason must be use in a specific context or anything ?
> According to Notify's docs:
> Returns the closed reason code for the notification. This is valid only after the "closed" signal is emitted.

Yeah, I read it but I don't remember a "SIGCLOSE" ^^. It may be a kind of hooks ? `notify_notification_add_action(notification : Notifynotification*, action : LibC::Char*, label : LibC::Char*, callback : Notifyactioncallback, user_data : Gpointer, free_func : Gfreefunc)`

2016-10-21 07:59 UTC, splattael approved these changes

2016-10-21 08:00 UTC, splattael commented
@Nephos Ready to merge? :shipit: :dancer:

2016-10-21 08:15 UTC, Nephos commented
ok!

2016-10-21 08:17 UTC, merged

2016-11-19 14:25 UTC, splattael commented
@Nephos Just a quick note that `libnotify.cr` `v0.2.0` was just released and your PR is included! :sparkles: :fireworks: 

Thanks again for your contribution :green_heart:

2016-11-19 14:31 UTC, Nephos commented
Thanks you for your time !